version: '3.6'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
  psql:
    image: postgres
    environment:
      - PGPASSWORD=password
    command: psql -h postgres -U username "assembleia_db"
    depends_on:
      - postgres

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      - KAFKA_CREATE_TOPICS=SessaoVotacaoResulted:1:1 # topic:partition:replicas
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
